name: "clearbed"
version: "1.0.0"
config-version: 2
profile: "clearbed"
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  clearbed:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  clearbed:
    +schema: seeds
